import type { Metadata } from "next";
import { Fustat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";

const fustat = Fustat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fustat.className} antialiased bg-[#1E1E1E] grain-texture`}
      >
        {children}
      </body>
    </html>
  );
}
