import Navbar from '@/components/layout/navbar';
import Footer from '@/components/layout/footer';
import Image from 'next/image';

export default function DisclaimerPage() {
  return (
    <>
      <Navbar />
    <main className="min-h-screen mx-auto w-full lg:px-10 px-4">
      {/* Banner */}
      <section className="w-full max-w-[1858px] mx-auto flex justify-center items-center lg:h-[518px] relative rounded-3xl overflow-hidden">
        <Image
          src="/images/disclaimer-banner.png"
          alt="Banner BG"
          fill
          className="object-cover object-center pointer-events-none select-none"
          priority
        />
        <div className="relative z-10 flex flex-col items-center justify-center w-full py-12">
          <h1 className="text-[#232323] text-4xl md:text-6xl font-semibold text-center mb-4">Disclaimer</h1>
          <p className="text-[#232323]/80 text-lg md:text-xl text-center font-light">Effective Date: April, 2025</p>
        </div>
      </section>
      {/* Disclaimer Content */}
      <section className="w-full flex justify-center px-2 py-12 max-w-[1858px] mx-auto">
        <div className="w-full bg-[#232323] rounded-3xl shadow-xl px-6 md:px-12 py-10 text-white text-base md:text-lg">
          <ol className="list-decimal list-inside space-y-6">
            <li>
              <b>Platform in Beta Phase</b>
              <p className="mt-2 text-white/90">
                This website, including all features, content, and functionality (collectively, the &quot;Platform&quot;), is operated by NeuralArc Global Pvt Ltd (&quot;NeuralArc&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) and is currently made available in beta for testing, evaluation, and limited public preview.<br />
                The Platform is provided strictly on an &quot;as is,&quot; &quot;as available,&quot; and experimental basis. NeuralArc makes no representations or warranties of any kind, express or implied, regarding the reliability, accuracy, or completeness of the Platform at this stage.
              </p>
            </li>
            <li>
              <b>No Professional Advice</b>
              <p className="mt-2 text-white/90">
                All information and content made available through this Platform, including AI-generated outputs, is for informational and illustrative purposes only.<br />
                Nothing on this Platform constitutes or shall be construed as legal, medical, financial, investment, business, or other professional advice. Users are solely responsible for independently verifying any information obtained through the Platform before acting or making decisions based on it.
              </p>
            </li>
            <li>
              <b>Artificial Intelligence and Output Liability</b>
              <p className="mt-2 text-white/90">
                The Platform may use AI, machine learning, or large language models to generate content. You acknowledge and accept that:
                <ul className="list-disc list-inside ml-6 mt-2">
                  <li>AI-generated content may be factually incorrect, incomplete, or biased;</li>
                  <li>Outputs are not guaranteed to be accurate, truthful, or contextually appropriate;</li>
                  <li>NeuralArc disclaims all liability for reliance on AI-generated outputs.</li>
                </ul>
                By using the Platform, you agree not to rely on AI-generated content for decisions of a personal, professional, legal, or financial nature without consulting qualified professionals.
              </p>
            </li>
            <li>
              <b>Limitation of Liability</b>
              <p className="mt-2 text-white/90">
                To the maximum extent permitted under applicable law, NeuralArc, its officers, directors, shareholders, affiliates, contractors, licensors, and employees shall not be liable for any direct, indirect, incidental, consequential, special, exemplary, or punitive damages arising out of or related to:
                <ul className="list-disc list-inside ml-6 mt-2">
                  <li>access to, use of, or inability to use the Platform;</li>
                  <li>errors, omissions, delays, or performance issues;</li>
                  <li>content generated by AI or user input;</li>
                  <li>cyberattacks, data loss, unauthorized access, or security breaches.</li>
                </ul>
                This limitation applies even if NeuralArc has been advised of the possibility of such damages, and regardless of the legal theory (contract, tort, strict liability, or otherwise) upon which the claim is based.
              </p>
            </li>
            <li>
              <b>Third-Party Services and Hosting</b>
              <p className="mt-2 text-white/90">
                This Platform is hosted on infrastructure provided by Vercel Inc. NeuralArc does not control Vercel&apos;s operations, security, or data policies.<br />
                By using this Platform, you consent to your data being processed and stored by Vercel and its subprocessors in accordance with their respective terms of service and privacy policies.<br />
                The Platform may also link to or incorporate third-party services or tools. NeuralArc accepts no responsibility or liability for any third-party content, data practices, or service reliability.
              </p>
            </li>
            <li>
              <b>Intellectual Property</b>
              <p className="mt-2 text-white/90">
                All intellectual property on this Platform—including, without limitation, code, software, content, branding, design elements, and AI-generated materials—are the exclusive property of NeuralArc or its licensors and are protected by applicable copyright, trademark, and patent laws.<br />
                You may not copy, reproduce, distribute, or use any part of the Platform without express prior written consent. Unauthorized use may result in civil and/or criminal liability.
              </p>
            </li>
            <li>
              <b>User Conduct and Acceptable Use</b>
              <p className="mt-2 text-white/90">
                You agree not to use the Platform for any unlawful, harmful, or unethical purpose. Prohibited uses include, but are not limited to:
                <ul className="list-disc list-inside ml-6 mt-2">
                  <li>Attempting to reverse-engineer or exploit the AI systems;</li>
                  <li>Uploading malicious code or compromising Platform security;</li>
                  <li>Generating content that is defamatory, infringing, obscene, deceptive, or discriminatory;</li>
                  <li>Circumventing usage limits, access controls, or platform restrictions.</li>
                </ul>
                Violation of these terms may result in immediate suspension or termination of access and may expose you to civil or criminal liability.
              </p>
            </li>
            <li>
              <b>Jurisdiction and Governing Law</b>
              <p className="mt-2 text-white/90">
                This Disclaimer and all matters arising from the use of this Platform shall be governed by and construed in accordance with the laws of India, without regard to conflict of laws.<br />
                You expressly submit to the exclusive jurisdiction of the courts of Pune, Maharashtra, for the resolution of any disputes.
              </p>
            </li>
            <li>
              <b>Changes to this Disclaimer</b>
              <p className="mt-2 text-white/90">
                NeuralArc reserves the right to amend, revise, or update this Disclaimer at any time without prior notice. Continued use of the Platform following any updates constitutes acceptance of the revised terms.
              </p>
            </li>
            <li>
              <b>Contact Information</b>
              <p className="mt-2 text-white/90">
                For questions, legal concerns, or notices related to this Disclaimer, please contact: support@neuralarc.ai
              </p>
            </li>
          </ol>
        </div>
      </section>
    </main>
      <Footer />
    </>
  );
} 